"""Arayüz metinleri (dil ayarı: config.display.language; oyunda F3 ile değişir)."""

TEXTS = {
    "en": {
        "title": "BEAT THE FLY",
        "subtitle": "Collect fruit. Dodge the swatter. Score more than your opponent in {secs} seconds.",
        "opponent": "Opponent",
        "controls": "LEFT / RIGHT to turn     UP to fly forward",
        "press_start": "Press SPACE to start",
        "you": "YOU",
        "go": "GO!",
        "time_up": "TIME!",
        "you_win": "YOU WIN!",
        "you_lose": "YOU LOSE",
        "tie": "TIE",
        "prize": "You won a prize!",
        "no_prize": "Try again!",
        "continue": "Press SPACE to continue",
        "fruits": "fruit",
        "hits": "hits",
        "stunned": "STUNNED",
        "seed": "round seed",
        # ödül
        "title_prize": "Beat the {name} and win a prize!",
        "title_prize_rule": "(prize needs at least {min} points and a {margin}-point lead)",
        "prize_show": "Show this screen to our team.",
        "prize_not_eligible": "Nice! Beat the {name} to win a prize.",
        "prize_below": "So close! A prize needs at least {min} points and a {margin}-point lead.",
        "prize_no_stock": "No prizes left today - but you made it onto the board!",
        # rakip seçimi
        "choose_title": "CHOOSE YOUR OPPONENT",
        "choose_hint": "LEFT / RIGHT to choose     SPACE to start",
        "opponent_pick": "You pick your opponent:",
        "avg_here": "Average score here: {x}",
        "desc_fly_brain": "A simulation of a real fruit-fly brain, running live. It decides with its own neurons.",
        "desc_heuristic": "A hand-written program that plans every move. Very hard to beat!",
        "desc_scripted": "A simple hand-written program: it goes for the nearest fruit.",
        "desc_replay": "A recorded run, replayed exactly as it happened.",
        "prize_tag": "PRIZE",
        "record_line": "Visitors won {w} of {n}",
        # baş harfler
        "enter_initials": "NEW HIGH SCORE!  Enter your initials",
        "initials_hint": "UP / DOWN letter     LEFT / RIGHT move     SPACE done",
        # skor tablosu
        "board_title": "LEADERBOARD",
        "board_today": "today",
        "board_all": "all time",
        "board_empty": "No scores yet - be the first!",
        "board_avg": "{name} (average)",
        "board_vs": "Visitors vs {name}:  {w} won  ·  {l} lost  ·  {t} tied",
        "board_prizes": "Prizes won: {n}   (today: {t})",
        # nasıl çalışır
        "how_title": "HOW DOES THE FLY PLAY?",
        "how_lines": [
            "The fly on the right is run by a simulation of a real fruit-fly brain:",
            "{neurons} neurons, wired exactly as mapped by the FlyWire project.",
            "We show it the game by stimulating its eye neurons:",
            "fruit: object detectors,  swatters: looming detectors.",
            "Its moves come from neurons that normally steer its legs (DNa01, DNa02)",
            "and from the giant fiber, which triggers escapes.",
            "The wiring is never trained or changed. We only tuned the numbers that",
            "translate between the game and the neurons, and its cruising speed.",
            "Same brain with its wires shuffled: it scores zero.",
        ],
        # nöron paneli
        "panel_live": "LIVE",
        "panel_recorded": "RECORDED",
        "panel_net": "{n} neurons · {m} million connections",
        "panel_spikes": "{n} spikes per second",
        "panel_rt": "simulated {x:.1f}x faster than real time",
        "panel_escape": "GIANT FIBER: ESCAPE!",
        "panel_bot_title": "NO BRAIN",
        "panel_bot_1": "This opponent is a hand-written program.",
        "panel_bot_2": "There are no neurons to show.",
        "panel_no_data": "This recording has no neuron data.",
        # beyin haritası
        "map_title": "BRAIN MAP · every dot is one neuron",
        "map_sub": "a dot lights up when its neuron fires",
        "map_back": "seen from behind",
        "map_top": "seen from above, head up",
        "map_l": "LEFT",
        "map_r": "RIGHT",
        "map_legs": "TO THE LEGS",
        "map_turn_l": "turn left",
        "map_turn_r": "turn right",
        "map_straight": "straight",
        "map_fruit": "eyes: fruit",
        "map_loom": "eyes: swatter",
        "map_decision": "decision neurons",
        "map_other": "other neurons",
        "map_active": "{k} neurons firing now",
        "map_source": "positions: FlyWire v783",
        "map_old": "This recording was made before the brain map existed, so it has no map data.",
        "map_missing": "Brain map data not found. Run: python -m flygame brain-download",
        # operatör
        "hold_esc": "Keep holding ESC to quit ... {s}",
        "reset_confirm": "Press F9 again within 3 s to reset the leaderboard",
        "reset_done": "Leaderboard reset (backup: {path})",
        "opponent_first": "Default opponent: {name}",
        "sound_on": "Sound on",
        "sound_off": "Sound off",
        "lang_name": "Language: English",
        "help_title": "OPERATOR KEYS",
        "help_lines": [
            "F1   show / hide this help",
            "F2   change the default opponent",
            "F3   language English / Turkish",
            "F4   sound on / off",
            "F9   twice: reset leaderboard (a backup is kept)",
            "F11  fullscreen on / off (not in kiosk mode)",
            "ESC  {esc}",
        ],
        "esc_kiosk": "hold {s} s to quit",
        "esc_normal": "quit",
    },
    "tr": {
        "title": "SİNEĞİ YEN",
        "subtitle": "Meyve topla. Sinekliğe yakalanma. {secs} saniyede rakibinden fazla puan yap.",
        "opponent": "Rakip",
        "controls": "SOL / SAĞ ile dön     YUKARI ile ileri uç",
        "press_start": "Başlamak için BOŞLUK tuşuna bas",
        "you": "SEN",
        "go": "BAŞLA!",
        "time_up": "SÜRE BİTTİ!",
        "you_win": "KAZANDIN!",
        "you_lose": "KAYBETTİN",
        "tie": "BERABERE",
        "prize": "Ödül kazandın!",
        "no_prize": "Tekrar dene!",
        "continue": "Devam için BOŞLUK tuşuna bas",
        "fruits": "meyve",
        "hits": "darbe",
        "stunned": "SERSEMLEDİ",
        "seed": "tur tohumu",
        "title_prize": "{name} rakibini yen, ödül kazan!",
        "title_prize_rule": "(ödül için en az {min} puan ve {margin} puan fark gerekir)",
        "prize_show": "Bu ekranı ekibimize göster.",
        "prize_not_eligible": "Güzel! Ödül için {name} rakibini yenmelisin.",
        "prize_below": "Az kaldı! Ödül için en az {min} puan ve {margin} puan fark gerekir.",
        "prize_no_stock": "Bugünlük ödül kalmadı - ama skor tablosuna girdin!",
        "choose_title": "RAKİBİNİ SEÇ",
        "choose_hint": "SOL / SAĞ ile seç     BOŞLUK ile başla",
        "opponent_pick": "Rakibini sen seçersin:",
        "avg_here": "Buradaki ortalama puanı: {x}",
        "desc_fly_brain": "Gerçek bir meyve sineği beyninin canlı simülasyonu. Kendi nöronlarıyla karar verir.",
        "desc_heuristic": "Her hamlesini planlayan, elle yazılmış bir program. Yenmesi çok zor!",
        "desc_scripted": "Basit, elle yazılmış bir program: en yakın meyveye gider.",
        "desc_replay": "Kaydedilmiş bir koşunun, olduğu gibi tekrarı.",
        "prize_tag": "ÖDÜL",
        "record_line": "Ziyaretçi galibiyeti: {w} / {n}",
        "enter_initials": "YENİ REKOR!  Baş harflerini gir",
        "initials_hint": "YUKARI / AŞAĞI harf     SOL / SAĞ geç     BOŞLUK tamam",
        "board_title": "SKOR TABLOSU",
        "board_today": "bugün",
        "board_all": "tüm zamanlar",
        "board_empty": "Henüz skor yok - ilk sen ol!",
        "board_avg": "{name} (ortalama)",
        "board_vs": "Ziyaretçiler - {name}:  {w} galibiyet  ·  {l} yenilgi  ·  {t} beraberlik",
        "board_prizes": "Kazanılan ödül: {n}   (bugün: {t})",
        "how_title": "SİNEK NASIL OYNUYOR?",
        "how_lines": [
            "Sağdaki sinek, gerçek bir meyve sineği beyninin simülasyonuyla yönetiliyor:",
            "{neurons} nöron, FlyWire projesinin çıkardığı bağlantılarla birebir.",
            "Oyunu ona göz nöronlarını uyararak gösteriyoruz:",
            "meyve: nesne algılayıcılar,  sineklik: yaklaşma algılayıcılar.",
            "Hareketleri, normalde bacaklarını yönlendiren nöronlardan (DNa01, DNa02)",
            "ve kaçışı başlatan dev liften geliyor.",
            "Bağlantılar hiç eğitilmedi, değiştirilmedi. Yalnızca oyun ile nöronlar",
            "arasındaki çeviri sayılarını ve seyir hızını biz ayarladık.",
            "Aynı beyin, bağlantıları karıştırılınca: sıfır puan.",
        ],
        "panel_live": "CANLI",
        "panel_recorded": "KAYIT",
        "panel_net": "{n} nöron · {m} milyon bağlantı",
        "panel_spikes": "saniyede {n} sinir sinyali",
        "panel_rt": "gerçek zamandan {x:.1f} kat hızlı simüle ediliyor",
        "panel_escape": "DEV LİF: KAÇ!",
        "panel_bot_title": "BEYİN YOK",
        "panel_bot_1": "Bu rakip elle yazılmış bir programdır.",
        "panel_bot_2": "Gösterilecek nöronu yok.",
        "panel_no_data": "Bu kayıtta nöron verisi yok.",
        # beyin haritası
        "map_title": "BEYİN HARİTASI · her nokta bir nöron",
        "map_sub": "nöron ateşlediğinde noktası yanar",
        "map_back": "arkadan görünüm",
        "map_top": "üstten görünüm, baş yukarıda",
        "map_l": "SOL",
        "map_r": "SAĞ",
        "map_legs": "BACAKLARA",
        "map_turn_l": "sola dön",
        "map_turn_r": "sağa dön",
        "map_straight": "düz",
        "map_fruit": "gözler: meyve",
        "map_loom": "gözler: sineklik",
        "map_decision": "karar nöronları",
        "map_other": "diğer nöronlar",
        "map_active": "şu an {k} nöron ateşliyor",
        "map_source": "konumlar: FlyWire v783",
        "map_old": "Bu kayıt beyin haritasından önce yapılmış; harita verisi yok.",
        "map_missing": "Beyin haritası verisi bulunamadı. Çalıştırın: python -m flygame brain-download",
        "hold_esc": "Çıkmak için ESC'yi basılı tutmaya devam et ... {s}",
        "reset_confirm": "Skor tablosunu sıfırlamak için 3 sn içinde tekrar F9",
        "reset_done": "Skor tablosu sıfırlandı (yedek: {path})",
        "opponent_first": "Varsayılan rakip: {name}",
        "sound_on": "Ses açık",
        "sound_off": "Ses kapalı",
        "lang_name": "Dil: Türkçe",
        "help_title": "OPERATÖR TUŞLARI",
        "help_lines": [
            "F1   bu yardımı göster / gizle",
            "F2   varsayılan rakibi değiştir",
            "F3   dil İngilizce / Türkçe",
            "F4   ses aç / kapat",
            "F9   iki kez: skor tablosunu sıfırla (yedek tutulur)",
            "F11  tam ekran aç / kapat (kiosk modunda değil)",
            "ESC  {esc}",
        ],
        "esc_kiosk": "çıkmak için {s} sn basılı tut",
        "esc_normal": "çık",
    },
}

# Baş harf girişi için alfabeler
ALPHABETS = {
    "en": "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
    "tr": "ABCÇDEFGĞHIİJKLMNOÖPRSŞTUÜVYZ",
}


def get_texts(lang: str) -> dict:
    return TEXTS.get(lang, TEXTS["en"])


def fmt_int(n: float, lang: str) -> str:
    """Binlik ayraçlı sayı (Türkçede nokta)."""
    s = f"{int(round(n)):,}"
    return s.replace(",", ".") if lang == "tr" else s
